#apiKey: null
#cluster: null
#clusterId: null
#command: null
container: pytorch/conda-cuda
#container: paperspace/pytorch
#experimentId: null
#ignoreFiles: null
#isPreemptible: true
#isPublic: null
#jobEnv: null
#machineType: K80
machineType: C3
#module: false
#name: null
#nodeAttrs: null
#ports: null
#project: null
projectId: prya1pizz
#python-command: false
#registryPassword: null
#registryUsername: null
#relDockerfilePath: null
#script: null
#shell: false
#startedByUserId: null
#useDockerfile: null
#workingDirectory: null
workspace: https://github.com/fcoclavero/vscvs.git
#workspaceArchive: null
#workspaceUrl: null
